"""The docker target's host build (``SHIPCREW_DOCKER_BUILD=host``), with fakes.

Fake ``pnpm`` / ``npm`` / ``docker`` executables are resolved through
``SHIPCREW_PNPM`` / ``SHIPCREW_NPM`` / ``SHIPCREW_DOCKER`` (``tools.resolve``);
see :mod:`tests.shipcrew.deploy_fakes`.
"""

from __future__ import annotations

import json
import shutil
import time
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

from omnigent.shipcrew.deploy_targets import DeployError
from omnigent.shipcrew.deploy_targets.docker import DockerTarget
from omnigent.shipcrew.deploy_targets.host_build import build_env, run_step
from omnigent.shipcrew.report import build_report
from omnigent.shipcrew.settings import DEFAULT_RUNTIME_IMAGE, ShipcrewSettings
from omnigent.shipcrew.store import Mission

from .deploy_fakes import DeployFakes
from .test_deploy_docker import MISSION, _git, _pid_alive, commit, deploy

SLUG = "polls-web-abc123"
PACKAGE = json.dumps(
    {
        "name": "polls",
        "scripts": {"build": "next build", "start": "next start"},
        "dependencies": {"next": "16.0.0"},
    }
)


@pytest.fixture
def fakes(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[DeployFakes]:
    f = DeployFakes(tmp_path / "fakes", monkeypatch)
    monkeypatch.setenv("FAKE_SECRET", "sk-do-not-leak")
    yield f
    f.kill_all(tmp_path / "state")


def _repo(tmp_path: Path, *, lockfile: str = "pnpm-lock.yaml", standalone: bool = True) -> Path:
    path = tmp_path / "repo"
    path.mkdir()
    _git(path, "init", "-q", "-b", "main")
    files = {
        "package.json": PACKAGE,
        lockfile: "lockfileVersion: '9.0'\n",
        ".gitignore": "node_modules\n.next\n",
        # A repo Dockerfile the host build must not use.
        "Dockerfile": "FROM node:22-alpine\nRUN pnpm install\n",
    }
    if standalone:
        files["fake-standalone"] = "1"
    (path / "public").mkdir()
    (path / "public" / "logo.svg").write_text("<svg/>")
    commit(path, files, "init")
    return path


def _settings(tmp_path: Path, **fields: Any) -> ShipcrewSettings:
    values: dict[str, Any] = {
        "deploy_target": "docker",
        "deploy_state_dir": tmp_path / "state",
        "deploy_health_timeout_s": 5.0,
        "tunnel_url_timeout_s": 5.0,
        **fields,
    }
    return ShipcrewSettings(**values)


def _image(fakes: DeployFakes, repo: Path) -> dict[str, Any]:
    sha = _git(repo, "rev-parse", "HEAD")
    return fakes.world()["images"][f"shipcrew/{SLUG}:{sha[:12]}"]


class TestHostBuild:
    def test_standalone_happy_path(self, tmp_path: Path, fakes: DeployFakes) -> None:
        repo = _repo(tmp_path)
        target = DockerTarget(_settings(tmp_path, node_heap_mb=1536))
        result = deploy(target, repo)
        assert result.url == "https://fake-1.trycloudflare.com"
        detail = result.detail
        assert detail["build_mode"] == "host-standalone"
        assert detail["package_manager"] == "pnpm"
        for key in ("install_s", "app_build_s", "prepare_s", "package_s", "build_s"):
            assert isinstance(detail[key], float), key
        assert detail["image_mb"] == 123.5
        # Install from the lockfile offline first, then the build, in the worktree.
        install, build = fakes.pm_calls()
        assert install["args"] == ["install", "--frozen-lockfile", "--prefer-offline"]
        assert build["args"] == ["run", "build"]
        assert install["cwd"] == build["cwd"]
        assert "/worktrees/" in install["cwd"]
        env = build["env"]
        assert (env["CI"], env["NEXT_TELEMETRY_DISABLED"]) == ("1", "1")
        assert env["NODE_OPTIONS"] == "--max-old-space-size=1536"
        assert env["FAKE_SECRET"] is None  # the server's secrets stay out
        # A runtime-only image from a generated Dockerfile, no network, outside the repo.
        (docker_build,) = fakes.calls("build")
        assert docker_build[docker_build.index("--network") + 1] == "none"
        assert "--file" not in docker_build
        image = _image(fakes, repo)
        assert image["labels"]["shipcrew.build"] == "host-standalone"
        dockerfile = image["dockerfile"]
        assert dockerfile.startswith("# Generated by shipcrew")
        assert f"FROM {DEFAULT_RUNTIME_IMAGE}" in dockerfile
        assert "RUN" not in dockerfile and "USER 10001:10001" in dockerfile
        assert '["/nodejs/bin/node", "server.js"]' in dockerfile
        assert "HEALTHCHECK" in dockerfile
        assert "standalone/server.js" in image["files"]
        assert "static/chunks/app.js" in image["files"]
        assert "public/logo.svg" in image["files"]
        assert not any(f.startswith("node_modules") for f in image["files"])
        assert not Path(image["context"]).exists()  # the temp context is removed
        assert str(repo) not in image["context"]
        # The container serves the app through the tunnel.
        assert fakes.world()["containers"][f"shipcrew-{SLUG}"]["labels"]["shipcrew.sha"]

    def test_second_deploy_reuses_node_modules_and_the_next_cache(
        self, tmp_path: Path, fakes: DeployFakes
    ) -> None:
        repo = _repo(tmp_path)
        target = DockerTarget(_settings(tmp_path))
        first = deploy(target, repo)
        assert "deps_from" not in first.detail
        cache = target.state_dir / SLUG / "cache"
        assert (cache / "node_modules" / ".installs").read_text() == "1"
        commit(repo, {"page.txt": "v2"})
        second = deploy(target, repo)
        assert second.detail["deps_from"] == "cache"
        # The same node_modules went through a second (no-op) install, the build
        # cache through a second build.
        assert (cache / "node_modules" / ".installs").read_text() == "2"
        assert (cache / "next-cache" / "runs").read_text() == "2"

    def test_missing_standalone_ships_the_built_app_with_prod_deps(
        self, tmp_path: Path, fakes: DeployFakes
    ) -> None:
        repo = _repo(tmp_path, standalone=False)
        target = DockerTarget(_settings(tmp_path))
        result = deploy(target, repo)
        assert result.detail["build_mode"] == "host-generic"
        assert result.note is not None and 'output: "standalone"' in result.note
        image = _image(fakes, repo)
        assert "FROM node:22-bookworm-slim" in image["dockerfile"]
        assert 'CMD ["npm", "start"]' in image["dockerfile"]
        files = image["files"]
        assert "app/package.json" in files and "app/.next/BUILD_ID" in files
        assert "app/node_modules/dep/index.js" in files
        assert "app/node_modules/devdep" not in files  # pruned
        assert not any(f.startswith(("app/.git/", "app/.next/cache")) for f in files)
        assert "app/Dockerfile" not in files
        prune = [c for c in fakes.pm_calls() if c["args"][:1] == ["prune"]]
        assert [c["args"] for c in prune] == [["prune", "--prod"]]
        assert prune[0]["cwd"].endswith("/app")  # the context copy, not the worktree
        # The worktree's own node_modules (stashed for next time) still has dev deps.
        assert (target.state_dir / SLUG / "cache" / "node_modules" / "devdep").is_dir()

    def test_npm_lockfile_uses_npm_ci(self, tmp_path: Path, fakes: DeployFakes) -> None:
        repo = _repo(tmp_path, lockfile="package-lock.json")
        deploy(DockerTarget(_settings(tmp_path)), repo)
        assert [c["pm"] for c in fakes.pm_calls()] == ["npm", "npm"]
        assert fakes.pm_calls()[0]["args"] == ["ci", "--prefer-offline", "--no-audit", "--no-fund"]

    def test_build_failure_keeps_the_old_container(
        self, tmp_path: Path, fakes: DeployFakes
    ) -> None:
        repo = _repo(tmp_path)
        target = DockerTarget(_settings(tmp_path))
        deploy(target, repo)
        old_sha = _git(repo, "rev-parse", "HEAD")
        commit(repo, {"fake-build-fail": "1"})
        with pytest.raises(DeployError, match="host build failed") as info:
            deploy(target, repo)
        assert info.value.kept_previous
        assert "Type error in app/page.tsx" in str(info.value)  # the log tail
        containers = fakes.world()["containers"]
        assert list(containers) == [f"shipcrew-{SLUG}"]
        assert containers[f"shipcrew-{SLUG}"]["labels"]["shipcrew.sha"] == old_sha
        assert len(fakes.calls("build")) == 1  # no image for the broken commit
        # The installed deps are still kept for the next deploy.
        assert (target.state_dir / SLUG / "cache" / "node_modules").is_dir()

    def test_install_failure_is_a_deploy_error(self, tmp_path: Path, fakes: DeployFakes) -> None:
        repo = _repo(tmp_path)
        commit(repo, {"fake-install-fail": "1"})
        target = DockerTarget(_settings(tmp_path))
        with pytest.raises(DeployError, match="pnpm install failed") as info:
            deploy(target, repo)
        assert "ERR_PNPM_FETCH_FAIL" in str(info.value)
        assert fakes.calls("build") == []

    def test_build_timeout_kills_the_build(self, tmp_path: Path, fakes: DeployFakes) -> None:
        repo = _repo(tmp_path)
        commit(repo, {"fake-build-sleep": "30"})
        target = DockerTarget(_settings(tmp_path, deploy_build_timeout_s=2.0))
        started = time.monotonic()
        with pytest.raises(DeployError, match="timed out") as info:
            deploy(target, repo)
        assert time.monotonic() - started < 15
        assert info.value.kept_previous
        pid_files = list((target.state_dir / "worktrees").glob("*.pid"))
        assert pid_files, "the fake build wrote its pid"
        assert not _pid_alive(int(pid_files[0].read_text()))

    def test_dockerfile_mode_uses_the_repo_dockerfile(
        self, tmp_path: Path, fakes: DeployFakes
    ) -> None:
        repo = _repo(tmp_path)
        target = DockerTarget(_settings(tmp_path, docker_build="dockerfile"))
        result = deploy(target, repo)
        assert result.detail["build_mode"] == "dockerfile"
        assert fakes.pm_calls() == []
        image = _image(fakes, repo)
        assert image["labels"]["shipcrew.build"] == "dockerfile"
        assert image["network"] is None
        assert "RUN pnpm install" in image["dockerfile"]

    def test_missing_package_manager_falls_back_to_the_dockerfile(
        self, tmp_path: Path, fakes: DeployFakes, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        repo = _repo(tmp_path)
        monkeypatch.setenv("SHIPCREW_PNPM", str(tmp_path / "missing"))
        bin_dir = tmp_path / "bin"  # git and cp, but no pnpm
        bin_dir.mkdir()
        for tool in ("git", "cp"):
            real = shutil.which(tool)
            assert real is not None
            (bin_dir / tool).symlink_to(real)
        monkeypatch.setenv("PATH", str(bin_dir))
        monkeypatch.setattr("omnigent.shipcrew.tools.KNOWN_DIRS", [])
        target = DockerTarget(_settings(tmp_path))
        result = deploy(target, repo)
        assert result.detail["build_mode"] == "dockerfile"
        assert result.note is not None and "pnpm is not installed" in result.note

    def test_repo_without_package_json_uses_its_dockerfile(
        self, tmp_path: Path, fakes: DeployFakes
    ) -> None:
        repo = _repo(tmp_path)
        _git(repo, "rm", "-q", "package.json")
        commit(repo, {})
        result = deploy(DockerTarget(_settings(tmp_path)), repo)
        assert result.detail["build_mode"] == "dockerfile"
        assert result.note is not None and "no package.json" in result.note


class TestPieces:
    def test_run_step_timeout_kills_the_process_group(self, tmp_path: Path) -> None:
        log = tmp_path / "build.log"
        script = tmp_path / "slow.sh"
        pidfile = tmp_path / "child.pid"
        script.write_text(f"#!/bin/sh\nsleep 30 &\necho $! > {pidfile}\nwait\n")
        script.chmod(0o755)
        with pytest.raises(Exception, match="timed out"):
            run_step([str(script)], tmp_path, {"PATH": "/usr/bin:/bin"}, log,
                     deadline=time.monotonic() + 1.0, label="build")  # fmt: skip
        assert not _pid_alive(int(pidfile.read_text()))  # the grandchild too
        assert "timed out" in log.read_text()

    def test_build_env_is_scrubbed(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-secret")
        monkeypatch.setenv("npm_config_registry", "https://registry.example")
        env = build_env(None)
        assert "ANTHROPIC_API_KEY" not in env and "NODE_OPTIONS" not in env
        assert env["npm_config_registry"] == "https://registry.example"
        assert env["CI"] == "1" and "PATH" in env

    def test_settings_from_env(self, monkeypatch: pytest.MonkeyPatch) -> None:
        settings = ShipcrewSettings.from_env()
        assert settings.docker_build == "host"
        assert settings.docker_runtime_image == DEFAULT_RUNTIME_IMAGE
        monkeypatch.setenv("SHIPCREW_DOCKER_BUILD", "Dockerfile")
        monkeypatch.setenv("SHIPCREW_NODE_HEAP_MB", "2048")
        monkeypatch.setenv("SHIPCREW_DOCKER_RUNTIME_IMAGE", "node:22-bookworm-slim")
        settings = ShipcrewSettings.from_env()
        assert settings.docker_build == "dockerfile"
        assert settings.node_heap_mb == 2048
        assert settings.docker_runtime_image == "node:22-bookworm-slim"
        monkeypatch.setenv("SHIPCREW_DOCKER_BUILD", "bogus")
        monkeypatch.setenv("SHIPCREW_NODE_HEAP_MB", "lots")
        settings = ShipcrewSettings.from_env()
        assert settings.docker_build == "host" and settings.node_heap_mb is None

    def test_report_shows_the_build_steps(self) -> None:
        mission = Mission(
            id=MISSION.id,
            title="Polls",
            repo_path="/r",
            repo_url=None,
            status="active",
            created_at=0,
            preview={
                "status": "live",
                "url": "https://x.trycloudflare.com",
                "sha": "a" * 40,
                "target": "docker",
                "updated_at": 1_700_000_000,
                "detail": {
                    "build_mode": "host-standalone",
                    "install_s": 2.0,
                    "app_build_s": 12.4,
                    "prepare_s": 0.3,
                    "package_s": 5.0,
                    "build_s": 19.7,
                    "image_mb": 261.0,
                },
            },
        )
        report = build_report(mission, [])
        assert (
            "build 20s (host-standalone: install 2s, app build 12s, context 0s, image 5s)"
            in report
        )
        assert "image 261.0 MB" in report
