"""The ship report: deterministic Markdown from the stored mission and tasks."""

from __future__ import annotations

import dataclasses

from omnigent.shipcrew.report import build_report, format_duration, wall_time_s
from omnigent.shipcrew.store import Assignee, Mission, Task

T0 = 1_790_000_000.0  # 2026-09-21 ...


def _mission(**fields: object) -> Mission:
    base: dict[str, object] = {
        "id": "m1",
        "title": "Tiny CLI",
        "repo_path": "/work/tiny",
        "repo_url": "https://github.com/acme/tiny",
        "status": "done",
        "created_at": int(T0),
        "plan_decisions": ["Split the CLI into 3 tasks"],
        "ship_status": "done",
        "ship_url": "https://tiny.vercel.app",
        "ship_finished_at": T0 + 3725,
        "ship_decisions": ["Linked project tiny"],
        "ship_cost_usd": 0.25,
    }
    base.update(fields)
    return Mission(**base)  # type: ignore[arg-type]


def _tasks() -> list[Task]:
    return [
        Task(
            id="t1",
            mission_id="m1",
            title="Parse | args",
            status="merged",
            pr_number=3,
            pr_url="https://github.com/acme/tiny/pull/3",
            ci_attempts=1,
            review={
                "verdict": "approve",
                "summary": "",
                "findings": [
                    {"file": "src/cli.js", "line": 4, "severity": "major", "message": "no --help"},
                    {"file": "src/cli.js", "line": 9, "severity": "minor", "message": "nit"},
                ],
            },
            cost_usd=1.5,
            started_at=T0,
            decisions=["Used node:util parseArgs"],
            interventions=[{"at": T0 + 60, "reason": "needs human approval: package.json"}],
        ),
        Task(
            id="t2",
            mission_id="m1",
            title="Security audit",
            role="security",
            status="merged",
            pr_number=4,
            review={"verdict": "approve", "summary": "no injection found", "findings": []},
            cost_usd=0.75,
            started_at=T0 + 100,
        ),
        Task(
            id="t3",
            mission_id="m1",
            title="Docs",
            status="backlog",
            assignee=Assignee("human", "ana"),
        ),
    ]


def test_full_report() -> None:
    report = build_report(_mission(), _tasks())
    assert report.startswith(
        "# Ship report: Tiny CLI\n\n- **Deployment:** https://tiny.vercel.app\n"
    )
    assert "- **Repository:** https://github.com/acme/tiny" in report
    assert "- **Status:** Shipped" in report
    assert "- **Total cost:** $2.50 (tasks $2.25, deploy $0.25)" in report
    assert "- **Wall time:** 1h 02m 05s (first task start to ship end)" in report
    assert "## Tasks (2 of 3 merged)" in report
    assert (
        "| 1 | Parse \\| args | developer | merged | [#3](https://github.com/acme/tiny/pull/3)"
        " | 1/3 | approve | $1.50 |"
    ) in report
    assert "| 2 | Security audit | security | merged | #4 | 0/3 | approve | $0.75 |" in report
    assert "| 3 | Docs | developer (human: ana) | backlog | - | 0/3 | - | $0.00 |" in report
    assert "### Plan\n\n- Split the CLI into 3 tasks" in report
    assert "### Parse | args\n\n- Used node:util parseArgs" in report
    assert "### Deploy\n\n- Linked project tiny" in report
    assert "- **Parse | args** `src/cli.js:4` [major] no --help" in report
    assert "nit" not in report  # minor findings are not "left open"
    assert (
        "- **Security audit**: status merged; PR #4; review approve; no injection found" in report
    )
    assert "(2026-09-21 14:14 UTC): needs human approval: package.json" in report
    assert report.endswith("_Generated by shipcrew at 2026-09-21 15:15 UTC._\n")


def test_is_deterministic() -> None:
    assert build_report(_mission(), _tasks()) == build_report(_mission(), _tasks())


def test_failed_ship_and_empty_sections() -> None:
    mission = _mission(
        ship_status="failed",
        ship_url=None,
        ship_error="deploy failed: missing env vars: API_KEY",
        plan_decisions=[],
        ship_decisions=[],
        ship_note=None,
    )
    task = Task(id="t", mission_id="m1", title="Only", status="merged")
    report = build_report(mission, [task])
    assert "- **Deployment:** not deployed" in report
    assert "- **Status:** Ship failed: deploy failed: missing env vars: API_KEY" in report
    assert "_No decisions were reported._" in report
    assert "## Open review findings (major and blocker)\n\n_None._" in report
    assert "_No security task in this mission._" in report
    assert "_None: the crew needed no human._" in report
    assert "- **Wall time:** n/a" in report


def test_protected_note_and_wall_time() -> None:
    mission = _mission(ship_note="HTTP 401: protected")
    assert "- **Note:** HTTP 401: protected" in build_report(mission, _tasks())
    assert wall_time_s(mission, _tasks()) == 3725
    assert wall_time_s(mission, []) is None
    assert format_duration(65) == "1m 05s"
    assert format_duration(7) == "7s"


def test_interventions_say_what_was_asked() -> None:
    tasks = _tasks()
    tasks[0] = dataclasses.replace(tasks[0], interventions=[
        {"at": T0 + 60, "reason": "x", "policy": "shipcrew_shell_allowlist",
         "preview": "npm install -D vitest"},
        {"at": T0 + 70, "reason": "x", "policy": "shipcrew_shell_allowlist", "preview": "sed -i"},
        {"at": T0 + 80, "reason": "x", "policy": "shipcrew_workflows_approval",
         "preview": ".github/workflows/ci.yml"},
    ])  # fmt: skip
    report = build_report(_mission(), tasks)
    assert (
        "- **Human interventions:** 3 (shipcrew_shell_allowlist 2, "
        "shipcrew_workflows_approval 1)" in report
    )
    assert "shipcrew_shell_allowlist: npm install -D vitest" in report


def test_no_intervention_summary() -> None:
    tasks = _tasks()
    tasks[0] = dataclasses.replace(tasks[0], interventions=[])
    assert "- **Human interventions:** 0" in build_report(_mission(), tasks)
